export const REVIEWS = [
  {
    name: "Jan van der Berg",
    location: "Amsterdam",
    rating: 5,
    date: "2 weken geleden",
    text: "Snelle service en zeer vakkundig. De schoorsteenveger was op tijd en heeft alles netjes achtergelaten. Aanrader!",
  },
  {
    name: "Maria Jansen",
    location: "Rotterdam",
    rating: 5,
    date: "1 maand geleden",
    text: "Professioneel en vriendelijk. Duidelijke uitleg over de staat van mijn schoorsteen. Prijs-kwaliteit verhouding is uitstekend.",
  },
  {
    name: "Peter de Vries",
    location: "Utrecht",
    rating: 5,
    date: "3 weken geleden",
    text: "Zeer tevreden! Snel geholpen en de vakman nam de tijd om alles goed uit te leggen. Veegbewijs direct ontvangen.",
  },
  {
    name: "Sophie Bakker",
    location: "Den Haag",
    rating: 5,
    date: "2 maanden geleden",
    text: "Uitstekende service. Camera inspectie was zeer grondig en ik kreeg direct een rapport. Top!",
  },
  {
    name: "Henk Vermeulen",
    location: "Eindhoven",
    rating: 5,
    date: "1 week geleden",
    text: "Luchtkanaal gereinigd en wat een verschil! Professioneel werk en eerlijke prijzen. Zeker een aanrader.",
  },
  {
    name: "Linda Smit",
    location: "Groningen",
    rating: 5,
    date: "3 weken geleden",
    text: "Vogelnest verwijderd en schoorsteen geveegd. Keurig werk en alles netjes opgeruimd. Bedankt!",
  },
  {
    name: "Tom Willems",
    location: "Breda",
    rating: 5,
    date: "1 maand geleden",
    text: "Zeer vakkundig en betrouwbaar. De afspraak verliep soepel en het werk was snel geklaard.",
  },
  {
    name: "Emma de Jong",
    location: "Nijmegen",
    rating: 5,
    date: "2 weken geleden",
    text: "Fantastische service! Vriendelijke vakman die zijn werk goed kent. Prijs was zoals afgesproken.",
  },
  {
    name: "Robert Mulder",
    location: "Tilburg",
    rating: 5,
    date: "4 weken geleden",
    text: "Schoorsteenkap geplaatst en schoorsteen geveegd. Alles perfect uitgevoerd. Zeer tevreden!",
  },
  {
    name: "Annemarie Visser",
    location: "Almere",
    rating: 5,
    date: "1 week geleden",
    text: "Snelle reactie en dezelfde week nog geholpen. Professioneel en netjes. Zeker een aanrader!",
  },
];
